import React from 'react';

function ReferenciasBibliograficas() {
  return (
    <div className="referencias-container" style={{maxWidth: '900px', margin: '0 auto', padding: '2rem 1rem'}}>
      <h1 style={{textAlign: 'center', marginBottom: '2rem'}}>Referencias Bibliográficas</h1>
      <ol style={{fontSize: '1.05rem', lineHeight: '1.7'}}>
        <li>Aguilera Arango, G. A., Rodríguez Henao, E., Chaparro Zambrano, H. N., &amp; Orduz Rodríguez, J. O. (2020). Estado actual de la investigación para el cultivo de guayaba en Colombia. Agronomía Mesoamericana, 31(3), 845–860. <a href="https://doi.org/10.15517/am.v31i3.42341" target="_blank" rel="noopener noreferrer">https://doi.org/10.15517/am.v31i3.42341</a></li>
        <li>Cárdenas Baquero, G. D., Arrazola Paternina, G., &amp; Villalba Cadavid, M. (2016). Frutas tropicales: fuente de compuestos bioactivos naturales en la industria de alimentos. Ingenium: Revista de la Facultad de Ingeniería, 17(33). <a href="https://revistas.usb.edu.co/index.php/Ingenium/article/view/2152" target="_blank" rel="noopener noreferrer">https://revistas.usb.edu.co/index.php/Ingenium/article/view/2152</a></li>
        <li>Collantes, R. D., Pitti, J. E., Jercovic, M., &amp; Atencio, R. (2021). Frutas con potencial como alimentos funcionales en Cerro Punta, Chiriquí, Panamá. Semilla del Este, 2(1), 1–11. <a href="https://revistas.up.ac.pa/index.php/semilla_este/article/view/2460" target="_blank" rel="noopener noreferrer">https://revistas.up.ac.pa/index.php/semilla_este/article/view/2460</a></li>
        <li>Estrada, H., Restrepo, C. E., Saumett, H., &amp; Pérez, J. (2018). Deshidratación osmótica y secado por aire caliente en mango, guayaba y limón para la obtención de ingredientes. Información Tecnológica, 29(3), 197–204. <a href="https://doi.org/10.4067/S0718-07642018000300197" target="_blank" rel="noopener noreferrer">https://doi.org/10.4067/S0718-07642018000300197</a></li>
        <li>Gabriele, R., Giosuè, A., Calabrese, I., &amp; Vaccaro, O. (2022). Recomendaciones dietéticas para la prevención de la aterosclerosis. Cardiovascular Research, 118(5), 1188–1204. <a href="https://doi.org/10.1093/cvr/cvab173" target="_blank" rel="noopener noreferrer">https://doi.org/10.1093/cvr/cvab173</a></li>
        <li>Huber Disla, N. (2022). ¿Es saludable la fruta? Derrocando mitos comunes sobre las frutas. T. Colin Campbell Center for Nutrition Studies. <a href="https://nutritionstudies.org/es/es-saludable-la-fruta-derrocando-mitos-comunes-sobre-las-frutas/" target="_blank" rel="noopener noreferrer">https://nutritionstudies.org/es/es-saludable-la-fruta-derrocando-mitos-comunes-sobre-las-frutas/</a></li>
        <li>Islam, M. R., Haque, A. R., Kabir, M. R., Hasan, M. M., Khushe, K. J., &amp; Hasan, S.M. K. (2021). Fruit by-products: The potential natural sources of antioxidants and α-glucosidase inhibitors. Journal of Food Science and Technology, 58(5), 1715–1726. <a href="https://doi.org/10.1007/s13197-020-04681-2" target="_blank" rel="noopener noreferrer">https://doi.org/10.1007/s13197-020-04681-2</a></li>
        <li>Jacoby, E., &amp; Keller, I. (2006). La promoción del consumo de frutas y verduras en América Latina: Buena oportunidad de acción intersectorial por una alimentación saludable. Revista Chilena de Nutrición, 33(supl. 1), 228–234. <a href="https://doi.org/10.4067/S0717-75182006000300003" target="_blank" rel="noopener noreferrer">https://doi.org/10.4067/S0717-75182006000300003</a></li>
        <li>Jurado Gámez, H., Cerón Córdoba, J. F., &amp; Bolaños, J. C. (2021). Aplicación de un probiótico (Lactobacillus reuteri ATCC 53608) microencapsulado en una bebida tipo sorbete a base de pulpa de fruta como alimento funcional y su aplicación en la industria alimentaria. Aglala, 12(2), 249–263. <a href="https://revistas.uninunez.edu.co/index.php/aglala/article/view/1993" target="_blank" rel="noopener noreferrer">https://revistas.uninunez.edu.co/index.php/aglala/article/view/1993</a></li>
        <li>Olguín, M. C., Posada, M. D., Revelant, G. C., Labourdette, V., Marinozzi, D. O., Venezia, M. R., &amp; Zingale, M. I. (2015). Efectos del consumo elevado de fructosa y sacarosa sobre parámetros metabólicos en ratas obesas y diabéticas. Revista Chilena de Nutrición, 42(2), 178–184. <a href="https://doi.org/10.4067/S0717-75182015000200006" target="_blank" rel="noopener noreferrer">https://doi.org/10.4067/S0717-75182015000200006</a></li>
        <li>Martínez, N., Del Mar Camacho, V., &amp; Martínez, J. (2008). Los compuestos bioactivos de las frutas y sus efectos en la salud. Nutrición Hospitalaria, 23(2), 64–68. <a href="https://www.sciencedirect.com/science/article/abs/pii/S1138032208756232" target="_blank" rel="noopener noreferrer">https://www.sciencedirect.com/science/article/abs/pii/S1138032208756232</a></li>
        <li>Riccardi, G., Giosuè, A., Calabrese, I., &amp; Vaccaro, O. (2022). Dietary recommendations for prevention of atherosclerosis. Cardiovascular Research, 118(5), 1188–1204. <a href="https://doi.org/10.1093/cvr/cvab173" target="_blank" rel="noopener noreferrer">https://doi.org/10.1093/cvr/cvab173</a></li>
        <li>Rodríguez Villamizar, S. M., &amp; Mendoza García, M. (2018). Modelo de agricultura inclusiva para los productores de frutas en el municipio de Lebrija, Santander - Colombia. Repositorio Universidad Autónoma de Bucaramanga. <a href="http://hdl.handle.net/20.500.12749/2149" target="_blank" rel="noopener noreferrer">http://hdl.handle.net/20.500.12749/2149</a></li>
        <li>Ramírez, V. M., Montoya Salazar, M., Serna Posada, M., &amp; Betancur Hoyos, E. D. (2022). Semilla de guayaba y potencial agroindustrial como aporte nutricional en productos panificables incluyendo economía circular. Revista Sennova, 7(1). <a href="https://doi.org/10.23850/23899573.5436" target="_blank" rel="noopener noreferrer">https://doi.org/10.23850/23899573.5436</a></li>
        <li>Yepes, S. M., Montoya Naranjo, L. J., &amp; Orozco Sánchez, F. (2008). Valorización de residuos agroindustriales - frutas - en Medellín y el sur del Valle del Aburrá, Colombia. Revista Facultad Nacional de Agronomía Medellín, 61(1), 4422–4431. <a href="https://www.redalyc.org/articulo.oa?id=179914077018" target="_blank" rel="noopener noreferrer">https://www.redalyc.org/articulo.oa?id=179914077018</a></li>
  <li>Maqsood, S., Adiamo, O., Ahmad, M., &amp; Mudgil, P. (2020). Bioactive compounds from date fruit and seed as potential nutraceutical and functional food ingredients. Food Chemistry, 308, Article 125522. <a href="https://doi.org/10.1016/j.foodchem.2019.125522" target="_blank" rel="noopener noreferrer">https://doi.org/10.1016/j.foodchem.2019.125522</a></li>
  <li>National Center for Biotechnology Information. (2023). Date fruits: Nutritional values, health benefits and future prospects. PubMed Central (PMC). <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10778573/" target="_blank" rel="noopener noreferrer">https://pmc.ncbi.nlm.nih.gov/articles/PMC10778573/</a></li>
  <li>La Vanguardia. (2021, agosto 29). Dátil: propiedades, beneficios, valor nutricional e historia. <a href="https://www.lavanguardia.com/comer/materia-prima/20210829/7665473/datil-propiedades-beneficios-valor-nutricional-historia.html" target="_blank" rel="noopener noreferrer">https://www.lavanguardia.com/comer/materia-prima/20210829/7665473/datil-propiedades-beneficios-valor-nutricional-historia.html</a></li>
  <li>Auguste Escoffier School of Culinary Arts. (2022, abril 8). How to make fruit pectin. <a href="https://www.escoffier.edu/blog/recipes/how-to-make-fruit-pectin/" target="_blank" rel="noopener noreferrer">https://www.escoffier.edu/blog/recipes/how-to-make-fruit-pectin/</a></li>
  <li>Aegon. (2023, septiembre 12). Propiedades de la manzana: Beneficios para tu salud y bienestar. <a href="https://blog.aegon.es/alimentacion/propiedades-de-la-manzana-beneficios-para-tu-salud-y-bienestar/" target="_blank" rel="noopener noreferrer">https://blog.aegon.es/alimentacion/propiedades-de-la-manzana-beneficios-para-tu-salud-y-bienestar/</a></li>
  <li>Ministerio de Agricultura, Pesca y Alimentación de España. (1969). Conservas vegetales. <a href="https://www.mapa.gob.es/ministerio/pags/biblioteca/hojas/hd_1969_04.pdf" target="_blank" rel="noopener noreferrer">https://www.mapa.gob.es/es/alimentacion/temas/conservas-vegetales.aspx</a></li>
      </ol>
    </div>
  );
}

export default ReferenciasBibliograficas;
